name: Deploy to GitHub Pages

on:
  # Adjust if your default branch is not "main"
  push:
    branches: [main]
  workflow_dispatch:

# Minimal permissions required for Pages deployments
permissions:
  contents: read
  pages: write
  id-token: write

# Avoid overlapping deploys
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Node 22 is the current default recommended by the official Astro action
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm

      # Prefer a lockfile for reproducible builds. If you don't have one, commit it.
      - name: Install dependencies
        run: npm ci

      # Build for the canonical repo on the custom domain (root path).
      # Forces Astro `site` and `base` so assets resolve at https://lichtfeld.io/ (no subpath).
      - name: Build (lichtfeld.io root)
        if: ${{ github.repository == 'MrNeRF/lichtfeld-studio-web' }}
        run: npm run build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SITE_URL: https://lichtfeld.io/
          BASE_PATH: /

      # Build for forks / project pages (e.g., https://<owner>.github.io/lichtfeld-studio-web/)
      # Lets astro.config.mjs auto-derive site/base from GITHUB_REPOSITORY (subpath).
      - name: Build (forks / project pages)
        if: ${{ github.repository != 'MrNeRF/lichtfeld-studio-web' }}
        run: npm run build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Upload the ./docs directory as the Pages artifact
      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./docs

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
